USE [master]
GO
/****** Object:  Database [test4]    Script Date: 10/4/2023 2:24:31 μ.μ. ******/
CREATE DATABASE [test4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'test4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\test4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'test4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\test4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [test4] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [test4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [test4] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [test4] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [test4] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [test4] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [test4] SET ARITHABORT OFF 
GO
ALTER DATABASE [test4] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [test4] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [test4] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [test4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [test4] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [test4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [test4] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [test4] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [test4] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [test4] SET  DISABLE_BROKER 
GO
ALTER DATABASE [test4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [test4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [test4] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [test4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [test4] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [test4] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [test4] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [test4] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [test4] SET  MULTI_USER 
GO
ALTER DATABASE [test4] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [test4] SET DB_CHAINING OFF 
GO
ALTER DATABASE [test4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [test4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [test4] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [test4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [test4] SET QUERY_STORE = OFF
GO
USE [test4]
GO
/****** Object:  User [Tester4]    Script Date: 10/4/2023 2:24:31 μ.μ. ******/
CREATE USER [Tester4] FOR LOGIN [Tester4] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [KYR-RYZEN\kyrlo]    Script Date: 10/4/2023 2:24:31 μ.μ. ******/
CREATE USER [KYR-RYZEN\kyrlo] FOR LOGIN [KYR-RYZEN\kyrlo] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [Tester4]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 10/4/2023 2:24:32 μ.μ. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[productId] [int] NOT NULL,
	[productName] [nchar](10) NULL,
	[price] [decimal](18, 3) NULL,
	[productCategoryId] [int] NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[productId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [test4] SET  READ_WRITE 
GO
